// Independent coverage contract: removing a scenario or its attachment must not produce a passing partial baseline.
export const WEB_PERFORMANCE_METRICS = [
  'home.fresh-context',
  'home.relaunch',
  'ledger.select-day',
  'ledger.open-detail',
  'ledger.save-memo',
  'ledger.save-memo.server-confirmed',
  'ledger.save-category',
  'ledger.save-category.server-confirmed',
  'ledger.previous-month',
  'ledger.return-month',
  'search.first',
  'search.first-open',
  'search.next-page',
  'search.change-keyword',
  'expense-stats.first',
  'expense-stats.period-3',
  'expense-stats.period-6',
  'expense-stats.period-12',
  'expense-stats.revisit',
  'assets.first',
  'assets.account-detail',
  'ledger.return-from-assets',
  'assets.revisit',
  'asset-stats.first',
  'asset-stats.period-6',
  'asset-stats.period-12',
  'asset-stats.period-all',
  'asset-stats.period-3',
  'asset-stats.revisit',
  'ledger.add',
  'ledger.add.server-confirmed',
  'ledger.delete',
  'ledger.delete.server-confirmed',
] as const;
