const US_STOCK_ALIASES: Record<string, string[]> = {
  AAPL: ['애플'],
  MSFT: ['마이크로소프트', '마소'],
  NVDA: ['엔비디아'],
  TSLA: ['테슬라'],
  AMZN: ['아마존'],
  META: ['메타', '페이스북', '페북'],
  GOOGL: ['구글', '알파벳'],
  GOOG: ['구글', '알파벳'],
  AVGO: ['브로드컴'],
  AMD: ['에이엠디', '암드'],
  NFLX: ['넷플릭스'],
  PLTR: ['팔란티어'],
  TSM: ['TSMC', '대만반도체', '대만 반도체'],
  ASML: ['에이에스엠엘'],
  ARM: ['암', 'arm'],
  SMCI: ['슈퍼마이크로', '슈마컴'],
  MSTR: ['마이크로스트래티지', '스트래티지'],
  COIN: ['코인베이스'],
  'BRK.B': ['버크셔', '버크셔 해서웨이'],
  JPM: ['제이피모건', 'JP모건'],
  BAC: ['뱅크오브아메리카', '뱅오아'],
  WMT: ['월마트'],
  COST: ['코스트코'],
  DIS: ['디즈니'],
  BA: ['보잉'],
  NKE: ['나이키'],
  QCOM: ['퀄컴'],
  ADBE: ['어도비'],
  ORCL: ['오라클'],
  CRM: ['세일즈포스'],
  SHOP: ['쇼피파이'],
  UBER: ['우버'],
  ABNB: ['에어비앤비'],
  RDDT: ['레딧'],
  HOOD: ['로빈후드'],
  SOFI: ['소파이'],
  NVO: ['노보노디스크'],
  LLY: ['일라이릴리'],
  VOO: ['뱅가드S&P500', '뱅가드 s&p500'],
  SPY: ['에스피와이', 'S&P500 ETF', 's&p500 etf'],
  QQQ: ['나스닥100', '나스닥100 ETF', '큐큐큐'],
  TQQQ: ['나스닥3배', '나스닥 3배', '티큐큐큐'],
  SQQQ: ['나스닥인버스3배', '나스닥 인버스 3배', '에스큐큐큐'],
  SOXX: ['반도체 ETF'],
  SOXL: ['반도체3배', '반도체 3배', '속슬'],
  SOXS: ['반도체인버스3배', '반도체 인버스 3배', '속스'],
  VTI: ['미국전체', '미국 전체', '미국전체시장'],
  VT: ['전세계주식', '전세계 주식'],
  DIA: ['다우 ETF', '다우지수 ETF'],
  IWM: ['러셀2000', '러셀2000 ETF'],
  ARKK: ['아크이노베이션', '아크 ETF'],
  SCHD: ['슈드', '배당성장 ETF', '미국배당 ETF'],
  JEPI: ['제피', '월배당 ETF'],
  JEPQ: ['제이피큐', '나스닥월배당', '나스닥 월배당'],
  VIG: ['배당성장 ETF'],
  DGRO: ['아이셰어즈배당성장', '배당성장 ETF'],
  XLK: ['기술주 ETF', '테크 ETF'],
  XLF: ['금융 ETF'],
  XLE: ['에너지 ETF'],
  GLD: ['금 ETF', '골드 ETF'],
  IAU: ['금 ETF', '골드 ETF'],
  SLV: ['은 ETF'],
  TLT: ['장기채 ETF', '미국장기채', '미국 장기채'],
  TMF: ['미국채3배', '미국채 3배'],
  BITO: ['비트코인 선물 ETF'],
  IBIT: ['블랙록 비트코인 ETF'],
};

export function getUsStockAliases(symbol: string) {
  return US_STOCK_ALIASES[symbol.toUpperCase()] || [];
}
